### ISSUE TITLE
warning opencv conflict

### ISSUE THREAD

**Issue by perchon** [cyp4x141/VINS-Fusion-noetic-Opencv4#1]
hello,I download your code ,after "carkin_make",I meet these warning,how can I do later?Thanks for your aplay

/usr/bin/ld: warning: libopencv_video.so.4.2, needed by /home/gzl/vf_ws/devel/lib/libvins_lib.so, may conflict with libopencv_video.so.3.4
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.4, needed by /home/gzl/vf_ws/devel/lib/libvins_lib.so, may conflict with libopencv_imgcodecs.so.4.2
/usr/bin/ld: warning: libopencv_core.so.3.4, needed by /usr/local/lib/libopencv_video.so.3.4.16, may conflict with libopencv_core.so.4.2
/usr/bin/ld: warning: libopencv_video.so.4.2, needed by /home/gzl/vf_ws/devel/lib/libvins_lib.so, may conflict with libopencv_video.so.3.4
/usr/bin/ld: warning: libopencv_imgcodecs.so.3.4, needed by /home/gzl/vf_ws/devel/lib/libvins_lib.so, may conflict with libopencv_imgcodecs.so.4.2
/usr/bin/ld: warning: libopencv_core.so.3.4, needed by /usr/local/lib/libopencv_video.so.3.4.16, may conflict with libopencv_core.so.4.2
[ 98%] Built target kitti_odom_test
[ 98%] Built target kitti_gps_test
[100%] Linking CXX executable /home/gzl/vf_ws/devel/lib/vins/vins_node
/usr/bin/ld: warning: libopencv_video.so.4.2, needed by /home/gzl/vf_ws/devel/lib/libvins_lib.so, may conflict with libopencv_video.so.3.4
/usr/bin/ld: warning: libopencv_core.so.3.4, needed by /usr/local/lib/libopencv_video.so.3.4.16, may conflict with libopencv_core.so.4.2
[100%] Built target vins_node

**Comment by cyp4x141** [comment]
have u ever installed other version opencv?  this may cause version conflict.

**Comment by cyp4x141** [comment]
The origin VINS-Fusion use opencv3 lib , I change it to opencv4 (the default version of **ubuntu20.04**+**ROS-noetic**). if you didn't install any other opencv3-depend package or opencv3, you should be able to run the HKUST's demo after package build.

**Comment by cyp4x141** [comment]
maybe try `$ **catkin build**` instead of catkin_make? If it can finish build ,try to run their demo see if it works.
